### 1. Importação de Bibliotecas
Realize a importação da biblioteca pandas.

In [52]:
### importando a biblioteca pandas
import pandas as pd

### 2. Importação da Base de Dados

Importe o arquivo 'Tabela_Clubes.csv' o transforme em um dataframe e mostre as informações.

In [54]:
### carregando o arquivo CSV em um DataFrame
df = pd.read_csv("Tabela_Clubes.csv")

### mostrando as informações gerais do DataFrame

### 3. Mostre as primeiras linhas do DataFrame

In [55]:
### mostrando as primeiras linhas do DataFrame
df.head()

,Ano,Pos.,Clubes,Vitorias,Derrotas,Empates,GolsF/S,Saldo,Qtd_Jogadores,Idade_Media,Estrangeiros,Valor_total,Media_Valor,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,2017,18,America-MG,10,10,18,30:47,-17,51,"24,8",0,27350000,536000,NaN,NaN,NaN,NaN
1,2017,7,Athletico-PR,16,9,13,54:37,17,52,24,3,37650000,724000,NaN,NaN,NaN,NaN
2,2017,6,Atletico-MG,17,8,13,56:43,13,50,"23,4",6,61350000,1230000,NaN,NaN,NaN,NaN
3,2017,11,Bahia,12,12,14,39:41,-2,48,"23,2",2,34900000,727000,NaN,NaN,NaN,NaN
4,2017,9,Botafogo,13,12,13,38:46,-8,45,"23,1",4,25550000,568000,NaN,NaN,NaN,NaN

### 4. Removendo Colunas sem informações.

In [ ]:
### Se observamos bem, podemos ver que temos quatro colounas sem nome e sem informações, ou seja valores nulos
### removendo as colunas sem nome
df = df.drop(columns=['Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'])
### mostrando as informações gerais do DataFrame após a remoção das colunas
df.info()

### 5. Quais os times aparecem na tabela e quantas vezes cada um aparece?

In [ ]:
### vamos ver quais os times aparecem na tabela e quantas vezes cada um aparece
df.value_counts('Clubes')

### 6. Quantos times diferentes temos no DataFrame?

In [57]:
### vamos contar o total de times únicos na tabela
df.value_counts('Clubes').count()

np.int64(34)

### 7. Quais os anos que aparecem no DataFrame?

In [59]:
### vamos ver quais anos aparecem na tabela
df.value_counts("Ano").sort_values
### vamos ordenar os anos de forma crescente

Ano
2008    20
2009    20
2010    20
2011    20
2012    20
2013    20
2014    20
2015    20
2016    20
2017    20
Name: count, dtype: int64

### 8. Quais os campeões de cada ano?

In [61]:
### vamos verificar os campeões de cada ano e ordenar por ano
df[df["Pos."] == 1][["Ano", "Clubes"]].sort_values("Ano")

      Ano       Clubes
187  2008     Flamengo
169  2009   Fluminense
148  2010  Corinthians
129  2011   Fluminense
107  2012     Cruzeiro
88   2013     Cruzeiro
64   2014  Corinthians
53   2015    Palmeiras
27   2016  Corinthians
13   2017    Palmeiras

### 9. Qual o time que foi mais vezes campeão?

In [63]:
### qual time apareceu mais vezes como campeão?
df[df["Pos."] == 1].groupby("Clubes").count()["Pos."].sort_values(ascending=False)

Clubes
Corinthians    3
Cruzeiro       2
Fluminense     2
Palmeiras      2
Flamengo       1
Name: Pos., dtype: int64

### 10. Agora uma piada 😄, quais times paulistas não aparecem nenhuma vez como campeão?

Responda com um print

In [ ]:
### seu código aqui

### 11. Qual o time com mais derrotas?

In [ ]:
### qual o time com mais derrotas?
df.groupby("Clubes").sum()["Derrotas"].sort_values(ascending=False)

### mostrando todas as informações do time com mais derrotas

### 12. Qual o time com menos derrotas?

In [64]:
### qual o time com menos derrotas?
df.groupby("Clubes").sum()["Derrotas"].sort_values()




### mostrando todas as informações do time com menos derrotas

Clubes
Santa Cruz         7
Santo Andre        8
Joinville         10
Parana            11
Guarani           13
Criciuma          18
Nautico           20
Prudente          23
Portuguesa        27
America-MG        30
Atletico-GO       39
Ceara             40
Goias             46
Ponte Preta       51
Figueirense       53
Chapecoense       54
Avai              54
Sport             71
Bahia             72
Vitoria           72
Coritiba          81
Athletico-PR      81
Vasco             84
Palmeiras         89
Cruzeiro          91
Atletico-MG       92
Internacional     95
Botafogo          97
Fluminense        97
Sao Paulo        100
Gremio           102
Santos           104
Corinthians      109
Flamengo         115
Name: Derrotas, dtype: int64

### 13. Qual o time com maior número de estrangeiros?

In [65]:
### qual o time com maior número de estrangeiros?

df.groupby("Clubes").sum()["Estrangeiros"].sort_values(ascending=False)

### mostrando todas as informações do time com mais estrangeiros

Clubes
Flamengo         54
Internacional    43
Cruzeiro         39
Sao Paulo        37
Corinthians      35
Botafogo         35
Atletico-MG      31
Fluminense       30
Vasco            29
Santos           29
Gremio           29
Palmeiras        27
Athletico-PR     26
Coritiba         22
Vitoria          19
Bahia            13
Sport            11
Figueirense      10
Chapecoense      10
Nautico           9
Goias             7
Ponte Preta       7
Criciuma          6
Avai              4
Portuguesa        3
Santo Andre       3
Parana            3
Ceara             2
America-MG        1
Prudente          1
Santa Cruz        1
Joinville         1
Atletico-GO       0
Guarani           0
Name: Estrangeiros, dtype: int64

### 14. qual o time com o menor número de estrangeiros?

In [66]:
### qual o time com menor número de estrangeiros?
df.groupby("Clubes").sum()["Estrangeiros"].sort_values()

Clubes
Atletico-GO       0
Guarani           0
Joinville         1
America-MG        1
Santa Cruz        1
Prudente          1
Ceara             2
Santo Andre       3
Portuguesa        3
Parana            3
Avai              4
Criciuma          6
Goias             7
Ponte Preta       7
Nautico           9
Chapecoense      10
Figueirense      10
Sport            11
Bahia            13
Vitoria          19
Coritiba         22
Athletico-PR     26
Palmeiras        27
Santos           29
Vasco            29
Gremio           29
Fluminense       30
Atletico-MG      31
Corinthians      35
Botafogo         35
Sao Paulo        37
Cruzeiro         39
Internacional    43
Flamengo         54
Name: Estrangeiros, dtype: int64

### 15. Bônus

Vamos criar um gráfico que mostre os maiores campeões presentes nessa base de dados

In [68]:
import matplotlib.pyplot as plt

# Vamos criar um gráfico de barras para visualizar os times com mais títulos
titulos = campeoes['Clubes'].value_counts()

plt.figure(figsize=(14, 8))
bars = plt.bar(titulos.index, titulos.values,
               color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd',
                      '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'],
               edgecolor='black', linewidth=0.5, alpha=0.8)

# Adicionar os valores em cima de cada barra
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.05,
             f'{int(height)}', ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.title('Times com Mais Títulos', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Clubes', fontsize=12, fontweight='bold')
plt.ylabel('Número de Títulos', fontsize=12, fontweight='bold')

# Ajustar a escala do eixo Y de 0 a 3
plt.ylim(0, 3)

# Melhorar a aparência dos eixos
plt.xticks(rotation=0, ha='right')
plt.yticks(range(0, 4))  # Apenas números inteiros de 0 a 3

# Adicionar grid para melhor leitura
plt.grid(axis='y', alpha=0.3, linestyle='--')

# Ajustar layout para evitar cortes
plt.tight_layout()

# Mostrar o gráfico
plt.show()

NameError: name 'campeoes' is not defined